### PR TITLE
Fanhattan build

### PR DESCRIPTION
**Pull request by arohter**

### CODE REVIEW

**Comment by arohter** [comment]
I dont see any security concerns here 👍

**Comment by fhops** [comment]
Build FAILURE: https://jenkins-android.fanhattan.com/job/build_exoplayer/2/

**Comment by fhops** [comment]
Build OK: https://jenkins-android.fanhattan.com/job/build_exoplayer/3/

**Comment by fhops** [comment]
Build OK: https://jenkins-android.fanhattan.com/job/build_exoplayer/6/

**Comment by fhops** [comment]
Build OK: https://jenkins-android.fanhattan.com/job/build_exoplayer/7/

**Pull request merged**
